---
version: '3.9'
services:
  fileserver:
    image: 'hub.gitee.com/autom-studio/fileserver:v1.22.0'
    ports:
      - '8001:80'
    restart: always
    volumes:
      - '/data/fileserver/uploads:/data/uploads'
      - '/data/fileserver/conf/nginx.conf:/usr/local/nginx/conf/nginx.conf'
      - '/data/fileserver/conf/.htpasswd:/usr/local/nginx/conf/.htpasswd'
